version: '3'
services:
  web:

  applicaciones:

  proxy:

  cache:

  mariadb:
    volumes:
      - ./volumen:/var/lib/mysql
    enviroment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: prueba
      MYSQL_PASSWORD: prueba
      MYSQL_DATABASE: prueba
  bc:

volumes:
