version: '3'
services:
  web:
    image: nginx
    ports:
      - "8080:80"
    links:
      - varnish
    volumes:
      - ./config/nginx/default:/etc/nginx/conf.d/default.conf
      - ./config/nginx/logs/nginx-error.log:/var/log/nginx/error.log
      - ./config/nginx/logs/nginx-access.log:/var/log/nginx/access.log
      - ./html:/var/www/html
    container_name: nginx
    restart: always

  applicaciones:

  proxy:
    build:
    context: .
      dockerfile: ./Proxy-Inverso/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - nginx
    links:
      - nginx
    container_name: varnish
    restart: unless-stopped

  cache:

  mariadb:
    volumes:
      - ./volumen:/var/lib/mysql
    enviroment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: prueba
      MYSQL_PASSWORD: prueba
      MYSQL_DATABASE: prueba
  bc:

volumes:
